[project]
name = "sarncss"
version = "1.0.0"
description = "idk just liba lib"
authors = [{ name = "sorncss" }]
readme = "README.md"
requires-python = ">=3.8"
license = { text = "MIT" }
dependencies = []

[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"